spring.application.name=global-solution
nasa.api.key=s9gF1rPUkfxgXPIEvKZ4sc5SiLbaM5hKTQGmkCSM
spring.datasource.username=rm564232
spring.datasource.password=260407
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL

jwt.secret=c2VuaGFTdXBlclNlY3JldGFHcmFuZGVPQmFzdGFudGVQYXJhU2VyVmFsaWRhZGFGaW5hbG1lbnRl
jwt.expiration=3600000

spring.jpa.hibernate.ddl-auto=update



