-- DDL das tabelas do projeto NEI (Near Earth Impact) - versão PostgreSQL
-- Baseado nas entidades JPA: Asteroid, CloseApproach, User

CREATE TABLE TB_ASTEROID (
    ID BIGSERIAL PRIMARY KEY,
    NASA_ID VARCHAR(255),
    NAME VARCHAR(255),
    ESTIMATED_DIAMETER_MIN_KM DOUBLE PRECISION,
    ESTIMATED_DIAMETER_MAX_KM DOUBLE PRECISION,
    ABSOLUTE_MAGNITUDE DOUBLE PRECISION,
    IS_POTENTIALLY_DANGEROUS BOOLEAN
);

CREATE TABLE TB_CLOSE_APPROACH (
    ID BIGSERIAL PRIMARY KEY,
    ASTEROID_ID BIGINT REFERENCES TB_ASTEROID(ID),
    APPROACH_DATE DATE,
    MISS_DISTANCE_KM DOUBLE PRECISION,
    RELATIVE_VELOCITY_KM_H DOUBLE PRECISION,
    ORBITING_BODY VARCHAR(255),
    RISK_LEVEL INTEGER
);

CREATE TABLE TB_USER (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    USERNAME VARCHAR(255),
    PASSWORD VARCHAR(255)
);
