-- DDL das tabelas do projeto NEI (Near Earth Impact) - versão MySQL
-- Baseado nas entidades JPA: Asteroid, CloseApproach, User

CREATE TABLE TB_ASTEROID (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NASA_ID VARCHAR(255),
    NAME VARCHAR(255),
    ESTIMATED_DIAMETER_MIN_KM DOUBLE,
    ESTIMATED_DIAMETER_MAX_KM DOUBLE,
    ABSOLUTE_MAGNITUDE DOUBLE,
    IS_POTENTIALLY_DANGEROUS BOOLEAN
);

CREATE TABLE TB_CLOSE_APPROACH (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ASTEROID_ID BIGINT,
    APPROACH_DATE DATE,
    MISS_DISTANCE_KM DOUBLE,
    RELATIVE_VELOCITY_KM_H DOUBLE,
    ORBITING_BODY VARCHAR(255),
    RISK_LEVEL INT,
    CONSTRAINT FK_CLOSE_APPROACH_ASTEROID FOREIGN KEY (ASTEROID_ID) REFERENCES TB_ASTEROID(ID)
);

CREATE TABLE TB_USER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    USERNAME VARCHAR(255),
    PASSWORD VARCHAR(255)
);
