FROM postgres:16-alpine

ENV POSTGRES_DB=nei_db
ENV POSTGRES_USER=nei_user
ENV POSTGRES_PASSWORD=nei_pass

# A imagem oficial do Postgres roda automaticamente qualquer .sql
# colocado em /docker-entrypoint-initdb.d/ na primeira inicialização
COPY ddl_postgres.sql /docker-entrypoint-initdb.d/01_ddl.sql

EXPOSE 5432
